version: 2

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/detergent
    binary: detergent
    ldflags:
      - -s -w -X github.com/fission-ai/detergent/internal/cli.Version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: DanielJonesEB
    name: detergent
